apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mauro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-mauro
  template:
    metadata:
      labels:
        app: demo-mauro
    spec:
      containers:
        - name: demo-mauro
          image: ghcr.io/azratul/mauro-project:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
